#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.

fib = []

a = 1
b = 1
for n in range(100):
    c = a + b
    a = b
    b = c
    if c >= 4000000:
        break
    else:
        fib.append(c)

total = 0
for f in fib:
    if f % 2 == 0:
        total = total + f

print(total)
